In [16]:
import pandas as pd
import numpy as np
from numpy import dtype

In [17]:
filename = './data/2_input'
with open(filename) as file:
    lines = [np.array(line.rstrip().split(' '), dtype=int) for line in file]

In [18]:
differences = [line[1:] - line[:-1] for line in lines]

In [44]:
difference = differences[0]
differences[:5]

[array([ 1,  1,  3,  1, -3]),
 array([3, 3, 1, 0]),
 array([2, 1, 1, 2, 3, 1, 4]),
 array([1, 1, 3, 5]),
 array([ 3,  1,  2,  3, -3,  2,  2])]

In [51]:
differences_ = [1 if (
        ((np.abs(difference) > 3).sum() == 0) & (
    (((difference > 0).sum() == len(difference)) | ((difference < 0).sum() == len(difference)))
)
) else 0 for difference in differences#[:5]
                ]
np.sum(differences_)

np.int64(341)

Part 2

In [65]:
def check_if_difference_ok(difference):
    result = (
            ((np.abs(difference) > 3).sum() == 0) & (
            ((difference > 0).sum() == len(difference)) | 
            ((difference < 0).sum() == len(difference))
         )
    )
    return result

In [75]:
def check_if_array_ok(line):
    difference = line[1:] - line[:-1]
    result = check_if_difference_ok(difference)
    if result:
        return 1
    else: 
        for i in range(len(line)):
            tmp_line = np.delete(line, i)
            difference = tmp_line[1:] - tmp_line[:-1]
            result = check_if_difference_ok(difference)
            if result:
                return 1
                break
        return 0

In [76]:
np.sum(
    [check_if_array_ok(line) for line in lines]
)

np.int64(404)

In [73]:
lines[:5]

[array([66, 67, 68, 71, 72, 69]),
 array([72, 75, 78, 79, 79]),
 array([38, 40, 41, 42, 44, 47, 48, 52]),
 array([86, 87, 88, 91, 96]),
 array([30, 33, 34, 36, 39, 36, 38, 40])]